apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: canary-readiness
spec:
  args:
    - name: canary-hash

  metrics:
    - name: canary-pod-readiness
      initialDelay: 30s
      interval: 10s
      count: 3
      successCondition: result[0] == 1
      failureCondition: result[0] < 1
      failureLimit: 1
      consecutiveErrorLimit: 4

      provider:
        prometheus:
          address: http://prometheus-server.prometheus.svc.cluster.local
          query: |
            (
              avg(
                kube_pod_status_ready{
                  namespace="canary-demo",
                  condition="true",
                  pod=~"canary-demo-{{args.canary-hash}}-.*"
                }
              )
            ) or vector(0)