apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: git-hello-world-
  namespace: argo-workflows

spec:
  serviceAccountName: argo-workflow
  entrypoint: run-script

  templates:
    - name: run-script
      inputs:
        artifacts:
          - name: repository
            path: /workspace/repository
            git:
              repo: https://github.com/brunobml/jenkins-argo.git
              revision: main

      container:
        image: busybox:1.36
        workingDir: /workspace/repository
        command:
          - /bin/sh
        args:
          - scripts/hello-world.sh